module.exports =  {
    ADD_HOST: 'ADD_HOST',
    DEL_HOST: 'DEL_HOST',
    UPDATE_HOST: 'UPDATE_HOST',
    CHECK_HOST: 'CHECK_HOST',
    CHECK_HOST_ALL: 'CHECK_HOST_ALL',
    CHECK_ACTIVE_HOST: 'CHECK_ACTIVE_HOST',
    CHECK_ACTIVE_HOST_ALL: 'CHECK_ACTIVE_HOST_ALL',
    EXCHANGE_HOST: 'EXCHANGE_HOST',
    FILTER_HOST: 'FILTER_HOST'
}