module.exports = {
    ADD_PLUGIN: 'ADD_PLUGIN',
    EXCHANGE_PLUGIN: 'EXCHANGE_PLUGIN',
    DEL_RELEAS_PLUGIN: 'DEL_RELEAS_PLUGIN',
    CHACK_ALL_PLUGIN: 'CHACK_ALL_PLUGIN',
    CHACK_RELEAS_PLUGIN: 'CHACK_RELEAS_PLUGIN',
    CHACK_DEV_PLUGIN: 'CHACK_DEV_PLUGIN'
}